version: '3.8'

services:
  frontend:
    build: 
      context: ./interview-challenge-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./interview-challenge-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./interview-challenge-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./interview-challenge-backend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    command: --port=3306
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=challengedb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: